version: '3.6'

services:

  server:
    container_name: calculation-server
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    command: python server.py -p 4
    ports:
      - 1234:1234

  # client:
  #   container_name: calculation-client
  #   build:
  #     context: ../
  #     dockerfile: docker/client/Dockerfile
  #   depends_on:
  #     - server
  #   links:
  #     - server:server